<?php

/**
 * PluginrtBlogPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7264 2010-03-01 21:58:09Z jwage $
 */
abstract class PluginrtBlogPage extends BasertBlogPage
{
  public function getTypeNice()
  {
    return 'Blog Post';
  }

  public function getYear()
  {
    return date('Y',strtotime($this->getPublishedFrom()));
  }

  public function getMonth()
  {
    return date('m',strtotime($this->getPublishedFrom()));
  }

  public function getDay()
  {
    return date('d',strtotime($this->getPublishedFrom()));
  }
}