<?php $cred = sfConfig::get('app_gn_blog_visitor_credential', 'visitor_blog') . "\n" ?>

<?php if(sfConfig::get('app_gn_blog_is_private', false)): ?>

all:
  is_secure: true
compare:
  credentials: <?php echo $cred ?>

<?php endif; ?>