gnBlogPage:
  actAs:
    gnSearchTemplate:
      fields:      [title, content, description, author_name]
  columns:
    author_name:      string(255)
    author_email:     string(255)
  inheritance:
    type:              concrete
    extends:           gnPage
